// Package seed applies a small, embedded starter catalog the first time the
// registry runs against an empty store. It makes a fresh local/OSS install
// (sandboxctl, docker-compose, `make run`) come up already populated — and
// gives the vector search something to rank — without a separate bootstrap
// step. It is idempotent: once any artifact exists, seeding is skipped.
package seed

import (
	"bytes"
	"context"
	_ "embed"
	"fmt"
	"io"

	"gopkg.in/yaml.v3"

	"github.com/tesserix/agentic-registry/internal/store"
	"github.com/tesserix/agentic-registry/pkg/api/v1alpha1"
)

//go:embed data/catalog.yaml
var catalog []byte

// IfEmpty applies the embedded starter catalog when the default namespace has
// no artifacts. Returns the number of artifacts applied (0 if the store was
// already populated). Embeddings are generated by the store on Apply.
func IfEmpty(ctx context.Context, st store.Store) (int, error) {
	counts, err := st.Counts(ctx, v1alpha1.DefaultNamespace, nil)
	if err != nil {
		return 0, fmt.Errorf("seed: count: %w", err)
	}
	total := 0
	for _, c := range counts {
		total += c
	}
	if total > 0 {
		return 0, nil // already populated — nothing to do
	}

	dec := yaml.NewDecoder(bytes.NewReader(catalog))
	applied := 0
	for {
		var obj v1alpha1.Object
		err := dec.Decode(&obj)
		if err == io.EOF {
			break
		}
		if err != nil {
			return applied, fmt.Errorf("seed: decode: %w", err)
		}
		if obj.Kind == "" && obj.Metadata.Name == "" {
			continue // blank document between separators
		}
		if _, _, err := st.Apply(ctx, obj); err != nil {
			return applied, fmt.Errorf("seed: apply %s/%s: %w", obj.Kind, obj.Metadata.Name, err)
		}
		applied++
	}
	return applied, nil
}
